### ISSUE TITLE
Arreglar atributos

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-Olatzaranzabe#1]
Los atributos en HTML tienen que tener los valores entre comillas `class="main"`. Cuidado con esto, que es un error sintáctico y podría hacer fallar la web en algunos navegadores.

**Comment by Olatzaranzabe** [comment]
Hola Nasiba, ya debería de aparecer corregido este issue, espero haber hecho bien el arreglo. Gracias!
