### ISSUE TITLE
Arreglar orden de css <links> en <head>

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-Olatzaranzabe#2]
Ouch! Parece que estamos intentado utilizar la fuente Rubik en nuestro css cuando todavía no la ha descargado la página. Igual si cambiamos el orden de esas etiquetas `link` la cosa se apaña ;)

![](https://media.giphy.com/media/OAd8SBimLJXOM/giphy.gif)

**Comment by Olatzaranzabe** [comment]
He cambiado el orden de las etiquetas link y he puesto primero el link con las fuentes y después he linkeado el css, así quedaría solucionado? es que he puesto a mirar en el css y parece como si no cogiera la etiqueta Rubik (ya que aparece escrito como muy oscuro).
