### ISSUE TITLE
Herencia

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-Olatzaranzabe#6]
¿Le damos cariño a la herencia?
Podemos empezar por ponerle algunas declaraciones generales al body, para que otros selectores las hereden.

Por ejemplo: el tamaño de fuente (que pensemos que más se va a usar), la familia y el color.

**Comment by Olatzaranzabe** [comment]
He puesto algunas características más. Sería suficiente así?

**Comment by nasivuela** [comment]
Ojo Olatz, que en tu último commit has borrado el body y se te ha quedado una llave de css sin cerrar!

Más despacito no se escapan estos detalles!
