### ISSUE TITLE
Centrar el título

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-Olatzaranzabe#8]
Parece que el título le ha cogido cariño a la cabecera. Vamos a ponerlo en su sitio, centrandolo horizontal y verticalmente!
Hay que:
- Hacer que el body, o una etiqueta madre de header y main ocupe todo el alto (vh mola ;)
- Quitar esos 100vh del main, por que con 100vh en main + el alto de la cabecera hace nos pasamos de alto y aparece la barra de scroll.
- Centrar el título, a darle caña a flex o a position absolute + transform :)

**Comment by Olatzaranzabe** [comment]
Como hago para que una vez borrado los 100vh del main, el main siga ocupando el espacio restante?
He puesto al body el 100vh y borrado del main, y el main se me ha hecho muy pequeña. Por otro lado, intentando centrar el título en ese main incorrecto lo único que he conseguido es que desaparezca :'(

**Comment by nasivuela** [comment]
Vale paso a paso:
- Una opción para que el main creza verticalmente es que sea un item flex! Si le ponemos a su madre display flex, podremos hacer que main crezca ocupando toda la altura disponible.

- Para centrar el título podemos volver a usar flex! Si ponemos a main `display flex`, podemos justificar y alinear sus hijas ;)

**Comment by Olatzaranzabe** [comment]
Ya lo he conseguido!
