### ISSUE TITLE
Versión tablet

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-Olatzaranzabe#9]
Cuando cierres los issues, ¿te atreves con la versión tablet?

![](https://media.giphy.com/media/3oKIPmMXKTqCujivh6/giphy.gif)

**Comment by Olatzaranzabe** [comment]
Hola Nas!
Ya he hecho la versión tablet o lo he intentado por lo menos.
Creo que he conseguido que se vea correctamente pero hay una cosa que no he entendido.
he escrito   
.lista{
    display: flex;
    justify-content: flex-end;

En una de las pruebas que he hecho al borrarlo desaparecía el main entero. No he entendido como pasaba eso.
Ya me dirás que tal está y si tengo que realizar más cambios!
